Repository openshift/knative-eventing, pull requests merged in 2018-11, with the labels that each got.

#2 add OWNERS_ALIASES for knative-eventing
  OWNERS
  OWNERS_ALIASES
Labels: size/M

#1 add OWNERS_ALIASES for knative-eventing
  OWNERS
  OWNERS_ALIASES
Labels: size/M

#4 Build image master
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, lgtm, size/S

#3 Openshift CI
  Makefile
  config/500-webhook.yaml
  openshift/admission-webhooks.yaml
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/fanoutsidecar/Dockerfile
  openshift/ci-operator/knative-images/in-memory-channel-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-test-images/k8sevents/Dockerfile
  openshift/e2e-tests-openshift.sh
  test/README.md
  test/crd.go
  test/e2e-tests.sh
  test/e2e/k8s_events_test.go
  test/e2e_flags.go
  test/image_paths.txt
  test/test_images/k8sevents/function.go
  test/test_images/k8sevents/kodata/LICENSE
  test/test_images/k8sevents/kodata/VENDOR-LICENSE
  test/upload-test-images.sh
Labels: approved, lgtm, size/L

#6 Run kubecon demo as part of e2e tests
  openshift/e2e-tests-openshift.sh
  openshift/kubecon-demo.sh
Labels: approved, lgtm, size/M
