Repository openshift/knative-eventing, pull requests merged in 2019-06, with the labels that each got.

#142 CI was here
  ci
Labels: approved, lgtm, size/XS

#144 Using 0.6.0 for next release
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#143 using latest Serving Operator (0.6.0) for our product
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/L

#145 Using eventing operator
  openshift/e2e-tests-openshift.sh
  openshift/release/knative-eventing-ci.yaml
Labels: approved, lgtm, size/XXL

#149 CI was here
  ci
Labels: approved, lgtm, size/XS

#151 correcting new imc image locations
  Makefile
  openshift/ci-operator/knative-images/imc-controller/Dockerfile
  openshift/ci-operator/knative-images/imc-dispatcher/Dockerfile
Labels: approved, lgtm, size/S

#152 Vendoring of our own images, like w/ eventing-core
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-kafka-v0.6.0.yaml
Labels: approved, lgtm, size/L

#153 Fix OpenShift Conformance test suite
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#154 adding finalizer subresource for product images too...
  openshift/release/knative-eventing-kafka-v0.6.0.yaml
Labels: approved, lgtm, size/XS

#156 Tweak release script master
  Makefile
  openshift/ci-operator/knative-images/kafka-channel-crd-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-crd-dispatcher/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-crd-webhook/Dockerfile
  openshift/release/generate-kafka.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/M

#157 adding missing test images
  openshift/ci-operator/knative-test-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-test-images/helloworld/Dockerfile
Labels: approved, lgtm, size/S

#159 Using eventing operator to install eventing
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, size/L

#165 release creation prep work
  openshift/release/create-release-branch.sh
Labels: approved, lgtm, size/XS

#166 ci was here
  ci
Labels: approved, lgtm, size/XS
