Repository openshift/knative-eventing, pull requests merged in 2019-07, with the labels that each got.

#170 Update master for recent
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/knative-test-images/latency/Dockerfile
  openshift/ci-operator/knative-test-images/sequencestepper/Dockerfile
Labels: approved, lgtm, size/S

#171 Patching RBAC fix to our 'vendor,ed' image/release yaml
  openshift/release/knative-eventing-v0.7.0.yaml
Labels: approved, lgtm, size/XS

#172 Use our own images on the 070 branch
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/XS

#174 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#175 Drop sendevent and sequencestepper test images
  openshift/ci-operator/knative-test-images/sendevent/Dockerfile
  openshift/ci-operator/knative-test-images/sequencestepper/Dockerfile
Labels: approved, size/S

#173 patch the operator, per build
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#177 removing files that do not make sense
  openshift/release/knative-eventing-kafka-knative-v0.7.0.yaml
  openshift/release/knative-eventing-kafka-v0.7.0.yaml
  openshift/release/knative-eventing-knative-v0.7.0.yaml
  openshift/release/knative-eventing-v0.7.0.yaml
Labels: approved, lgtm, size/XXL

#185 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#180 Update catalogsource yaml to v0.7.1
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/L

#188 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#187 Install Strimzi, and remove Knative build
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#209 SRVKE-117 update cm catalogsource to released versions
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/S

#212 CI configuration expects images tagged ":ci", not ":latest"
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS
