Repository openshift/knative-eventing, pull requests merged in 2019-05, with the labels that each got.

#84 one more release trigger
  ci
Labels: approved, lgtm, size/XS

#82 Add knative-eventing-v0.6.0.yaml
  openshift/release/knative-eventing-v0.6.0.yaml
Labels: approved, lgtm, size/XL

#79 syncing latest files w/ openshift master
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/knative-images/cronjob_receive_adapter/Dockerfile
  openshift/ci-operator/knative-images/sources-controller/Dockerfile
  openshift/ci-operator/knative-test-images/transformevents/Dockerfile
  openshift/e2e-tests-openshift.sh
  openshift/release/knative-eventing-v0.5.0.yaml
Labels: size/XXL

#87 Update ci-config generator to use OpenShift 4.1
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm, size/XS

#85 Latest version from serving, borrowed
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/M

#86 Removing the admission yaml, not needed w/ OCP 4
  openshift/admission-webhooks.yaml
Labels: size/M

#92 Fix machineset selector
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#95 Update filez for master
  Makefile
  openshift/ci-operator/knative-images/apiserver_receive_adapter/Dockerfile
  openshift/ci-operator/knative-images/in-memory-channel-dispatcher/Dockerfile
  openshift/e2e-tests-openshift.sh
  openshift/release/resolve.sh
Labels: lgtm, size/S

#97 New image rename and better release resolve
  Makefile
  openshift/ci-operator/knative-images/sources_controller/Dockerfile
  openshift/release/generate-kafka.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
  openshift/release/update-to-head.sh
Labels: lgtm, size/M

#98 Adding new approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#99 latest, greatest filez
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#103 CI was here
  ci
Labels: approved, lgtm, size/XS

#105 Update Maistra to 0.10 and disable sidecar injection
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#109 Adding latest maistra patch to master
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#112 Update script to fail fast and use the repo name in the hub command
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/XS

#114 CI was here...
  ci
Labels: approved, lgtm, size/XS

#117 Adding OLM for 0.6.0
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/L

#118 Adding OLM for 0.6.0
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/L

#111 Install Knative Serving via Operator and minimal Istio
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/L

#123 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#126 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#125 Going to use serving 0.6.0 operator, that installs Maistra
  openshift/e2e-tests-openshift.sh
Labels: approved, size/L

#129 Adding new image...
  Makefile
  openshift/ci-operator/knative-images/imc/Dockerfile
Labels: approved, lgtm, size/XS

#130 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#135 using latest OLM generated file
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/M

#133 remove sources
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#137 Remove the KnativeServing dep and rely on OwnerRef to show resources
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/S

#139 Latest version of the re-generated CS
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, size/L
