Repository openshift/knative-eventing, pull requests merged in 2019-10, with the labels that each got.

#283 adding serving/serverless/sm operators
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-v0.8.0.yaml
  openshift/serverless/operator-install.yaml
Labels: approved, lgtm, size/L

#287 Backporting patch from 071 t0 08x line
  openshift/release/knative-eventing-v0.8.0.yaml
Labels: approved, lgtm, size/XS

#288 re-enabling OLM files for upstream override + clean ups
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/M

#289 Sync knative-eventing-ci.yaml, re SRVKE-160
  openshift/release/knative-eventing-ci.yaml
Labels: approved, lgtm, size/XS

#292 Build binaries w/ 1.13
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, size/XS

#291 No more 4.1 runs on next, just ocp 4.2
  Makefile
Labels: approved, size/XS

#294 master fix
  Makefile
Labels: size/XS

#298 Prepare of release next work, with two patches to ensure tests run
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/patches/001-no-random-namespace-names.patch
  openshift/patches/002-imc-ocp-rbac.patch
  openshift/release/generate-release.sh
  openshift/release/update-to-head.sh
  openshift/serverless/operator-install.yaml
Labels: approved, lgtm, size/XL

#306 Apply NetworkPolicy patch (see SRVKE-130)
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-v0.9.0.yaml
Labels: approved, lgtm, size/S

#309 CI was here...:fire:
  ci
Labels: approved, lgtm, size/XS

#312 Yaml fix 090
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
Labels: approved, lgtm, size/M

#320 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#319 :robot: CI was here...:fire:
  ci
Labels: approved, lgtm, size/XS

#322 We still do test on 4.1, hence the OLM fu is back :fire:
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#323 Using images we build during CI
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/XS

#327 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#330 Adding finalizer RBAC for generic channel
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-v0.8.0.yaml
Labels: approved, lgtm, size/XS

#335 remoive helloworld
  openshift/ci-operator/knative-test-images/helloworld/Dockerfile
Labels: approved, lgtm, size/XS

#331 Adding finalizer RBAC for generic channel
  openshift/e2e-tests-openshift.sh
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-v0.9.0.yaml
  test/e2e/broker_channel_flow_test.go
Labels: approved, size/M

#337 reflect multiple OCP runs
  Makefile
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm, size/XS
