Repository openshift/knative-eventing, pull requests merged in 2019-11, with the labels that each got.

#341 Release automation and documentation.
  Makefile
  README.md
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/update-ci.sh
  openshift/release/README.md
  openshift/release/create-release-branch.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/L

#345 changes towards 0.10 / srvless 1.2.0
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/serverless/operator-install.yaml
Labels: approved, lgtm, size/XXL

#340 changes towards 0.10 / srvless 1.2.0
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/serverless/operator-install.yaml
Labels: approved, lgtm, size/XXL

#349 Add aliok as approver and reviewer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#351 Serverless 120 goes 090 and deployments
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/release/knative-eventing-v0.9.0.yaml
  openshift/serverless/operator-install.yaml
Labels: approved, lgtm, size/XXL

#352 updates of the OLM for serving
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/S

#354 updates of the OLM for serving
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/S

#353 updates of the OLM for serving
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/S
