Repository openshift/knative-eventing, pull requests merged in 2019-04, with the labels that each got.

#38 Run release-v0.4.1 through CI
  ci
Labels: approved, lgtm, size/XS

#39 Houskeeping ocp files and add matzew owner
  Makefile
  OWNERS_ALIASES
  openshift/e2e-tests-openshift.sh
  openshift/release/README.md
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/L

#40 Olm manifest and catalogsource
  openshift/olm/knative-eventing-sources.crd.yaml
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-eventing.crd.yaml
  openshift/olm/knative-eventing.package.yaml
  openshift/olm/knative-eventing.v0.4.1.clusterserviceversion.yaml
Labels: size/XXL

#41 Rename
  openshift/e2e-tests-openshift.sh
  test/e2e/single_event_test.go
Labels: size/S

#44 Ci trigger
  ci
Labels: approved, lgtm, size/XS

#43 CI was here
  ci
Labels: size/XS

#42 Run Origin's conformance test suite via specific target
  Makefile
  openshift/e2e-tests-openshift.sh
  openshift/origin-e2e-job.yaml
Labels: approved, lgtm, size/L

#46 Replaces fix like serving PR #60
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-eventing.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#45 Release yaml v0.4.1
  Makefile
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-v0.4.1.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XL

#48 Release yaml master
  Makefile
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/M

#47 Release yaml v0.5.0
  Makefile
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-v0.5.0.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XXL

#52 Adding initial readme
  README.md
Labels: approved, lgtm, size/L

#57 Update latest
  ci
  openshift/e2e-tests-openshift.sh
  openshift/release/resolve.sh
Labels: size/M

#58 Adding release generator
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/release/generate-release.sh
Labels: approved, lgtm, size/M

#59 Adding finalizers
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/XS

#49 Run Origin's conformance test suite via specific target
  Makefile
  openshift/e2e-tests-openshift.sh
  openshift/origin-e2e-job.yaml
Labels: approved, lgtm, size/L

#61 Updating openshift specific files.
  openshift/olm/knative-eventing-sources.crd.yaml
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-eventing.crd.yaml
  openshift/olm/knative-eventing.package.yaml
  openshift/olm/knative-eventing.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XXL

#62 Improving resolver
  .gitignore
  openshift/release/knative-eventing-v0.5.0.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/L

#63 Granting some rights
  config/200-webhook-clusterrole.yaml
  openshift/e2e-tests-openshift.sh
  test/e2e/broker_trigger_test.go
Labels: approved, lgtm, size/S

#65 Adding webhook fix to generated file
  openshift/release/knative-eventing-v0.5.0.yaml
Labels: approved, lgtm, size/XS

#64 remove files, execpt for the (newly generated) catalogsource
  openshift/olm/README.md
  openshift/olm/knative-eventing-sources.crd.yaml
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-eventing.crd.yaml
  openshift/olm/knative-eventing.package.yaml
  openshift/olm/knative-eventing.v0.4.1.clusterserviceversion.yaml
Labels: approved, size/XXL

#67 Operator fixes
  config/300-broker.yaml
  config/300-channel.yaml
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-v0.5.0.yaml
Labels: approved, lgtm, size/L

#68 Update openshift bits
  .gitignore
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/knative-images/filter/Dockerfile
  openshift/ci-operator/knative-images/ingress/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-dispatcher/Dockerfile
  openshift/ci-operator/knative-images/pong/Dockerfile
  openshift/ci-operator/knative-images/sendevent/Dockerfile
  openshift/e2e-tests-openshift.sh
  openshift/olm/README.md
  openshift/olm/knative-eventing-sources.crd.yaml
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-eventing.crd.yaml
  openshift/olm/knative-eventing.package.yaml
  openshift/olm/knative-eventing.v0.4.1.clusterserviceversion.yaml
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-v0.5.0.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XXL

#69 CI was here
  openshift/ci
Labels: approved, lgtm, size/XS

#71 Hot fix for SRVKE-70
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/S

#72 SRVKE-77 fix
  config/200-broker-clusterrole.yaml
  openshift/release/knative-eventing-v0.5.0.yaml
Labels: size/S

#70 remove files from release generation
  openshift/release/generate-release.sh
Labels: approved, lgtm, size/XS

#73 Adding generated CS from latest manifestival
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, size/XXL

#74 OLM updates
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/S

#75 Non priviliged
  cmd/webhook/main.go
  config/400-webhook-service.yaml
Labels: approved, lgtm, size/XS

#80 CI generator and registry changes inside
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#77 Broker rbac fixes
  config/200-broker-clusterrole.yaml
  config/200-controller-clusterrole.yaml
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/release/knative-eventing-v0.5.0.yaml
Labels: approved, lgtm, size/L

#83 Some more rbac fun
  config/200-controller-clusterrole.yaml
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  openshift/release/knative-eventing-v0.5.0.yaml
Labels: approved, lgtm, size/M
