Repository openshift/knative-eventing, pull requests merged in 2019-09, with the labels that each got.

#270 Adding NetworkPolicy workaround for webhook
  openshift/release/knative-eventing-v0.7.1.yaml
Labels: approved, lgtm, size/S

#267 Increase CPU requests from 2 to 4
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm, size/XS

#273 adding fix for kafka-webhook
  openshift/release/knative-eventing-kafka-v0.7.1.yaml
Labels: approved, lgtm, size/S

#271 Srvke 134 oc all backport
  config/200-clusterrole-namespaced.yaml
  openshift/release/knative-eventing-v0.7.1.yaml
Labels: approved, lgtm, size/M

#278 Remove latency image to master
  openshift/ci-operator/knative-test-images/latency/Dockerfile
Labels: approved, lgtm, size/XS
