Repository openshift/knative-eventing, pull requests merged in 2019-08, with the labels that each got.

#214 e2e-tests-openshift.sh github.com/knative -> knative.dev update
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#215 Move catalogsource to the same namespace with subscription
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#220 Remove all kafka bits master
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/knative-images/kafka-channel-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-crd-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-crd-dispatcher/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-crd-webhook/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-dispatcher/Dockerfile
  openshift/ci-operator/knative-test-images/sendevent/Dockerfile
  openshift/release/generate-kafka.sh
Labels: approved, lgtm, size/M

#222 run e2e test in 35m and create SA
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#219 Remove all kafka bits
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/knative-images/kafka-channel-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-crd-controller/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-crd-dispatcher/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-crd-webhook/Dockerfile
  openshift/ci-operator/knative-images/kafka-channel-dispatcher/Dockerfile
  openshift/ci-operator/knative-test-images/sendevent/Dockerfile
  openshift/e2e-tests-openshift.sh
  openshift/release/generate-kafka.sh
Labels: approved, lgtm, size/M

#228 Knative.dev/eventing move for master
  openshift/ci-operator/generate-ci-config.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/M

#224 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#240 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#242 Move olm namespace to openshift-marketplace after OpenShift 4.2
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#245 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#246 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#238 New operator
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-ci.yaml
Labels: approved, lgtm, size/XXL

#249 tmp go back to non TP1 operator
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#250 tweaks for serving_TP1, which NO LONGER installs maistra
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/L

#256 use the latest file override
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/XS
