Repository openshift/knative-eventing, pull requests merged in 2020-07, with the labels that each got.

#692 Disable TestFlowsParallel and TestFlowsSequence
  test/e2e/parallel_test.go
  test/e2e/sequence_test.go
Labels: approved, area/test-and-release, lgtm

#673 Modify scripts to be reusable in serverless-operator repo
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#670 Modify scripts to be reusable in serverless-operator repo
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#671 Modify scripts to be reusable in serverless-operator repo
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#697 Update CI yaml to include sugar-controller
  openshift/e2e-common.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm

#699 Drop knative-eventing-channel-broker-ci.yaml
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved

#702 Only set TRACING_CONFIG's namespace differently if needed
  openshift/e2e-common.sh
Labels: approved

#696 Update channel broker image urls/names
  openshift/e2e-common.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-channelbroker-ci.yaml
  openshift/release/knative-eventing-ci.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm

#715 Remove unused code
  openshift/e2e-common.sh
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm

#716 Modify scripts for reusing v0.15.2
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#721 Test the images built in this PR (not via operator)
  openshift/e2e-common.sh
Labels: approved, lgtm

#724 Add storage version migration image.
  Makefile
  openshift/ci-operator/knative-images/migrate/Dockerfile
Labels: approved, lgtm

#722 [RELEASE-v0.15.2] Add storage version migration image.
  Makefile
  openshift/ci-operator/knative-images/migrate/Dockerfile
Labels: approved, lgtm

#723 [RELEASE-v0.16.0] Add storage version migration image.
  Makefile
  openshift/ci-operator/knative-images/migrate/Dockerfile
Labels: approved, lgtm
