Repository openshift/knative-eventing, pull requests merged in 2020-04, with the labels that each got.

#508 generate channel broker yamls
  openshift/release/generate-release.sh
Labels: approved

#512 Remove patch that was needed for ServiceMesh; We are now on Kourier
  openshift/999-webhook-policy_append.patch
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#513 Updating patches to latest
  openshift/patches/002-imc-ocp-rbac.patch
  openshift/patches/009-disable-auto-mt-brokers.patch
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#515 Removing myself from owners/reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#520 Update operators
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm

#523 Updates to e2e
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/patches/010-trigger_dependency-skip_tests.patch
Labels: approved, lgtm

#525 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#527 Adding the mt broker yamls
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm

#529 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, lgtm

#530 First round of MT broker enabled tests...
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm

#535 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#538 Remove the skipping of the test
  openshift/patches/010-trigger_dependency-skip_tests.patch
Labels: approved, lgtm

#536 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#542 Test clean up
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm

#539 Port trigger schema fix
  config/core/resources/trigger.yaml
  openshift/e2e-tests-openshift.sh
  openshift/release/knative-eventing-v0.13.0.yaml
  test/e2e/trigger_dependency_annotation_test.go
Labels: approved, area/test-and-release, lgtm

#540 CI was here...:fire:
  ci
Labels: approved, lgtm

#552 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, lgtm
