Repository openshift/knative-eventing, pull requests merged in 2020-03, with the labels that each got.

#469 Port trigger fix ocp
  pkg/apis/eventing/v1alpha1/trigger_conversion.go
  test/e2e/trigger_dependency_annotation_test.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, lgtm, size/S

#471 CI was here...:fire:
  ci
Labels: approved, lgtm, size/XS

#472 Remove myself from approvers/reviewers
  OWNERS_ALIASES
Labels: approved, size/XS

#475 adding smoother install for serverless
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#478 adding smoother install for serverless
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#482 Update to latest pkg 0.13 (#2727)
  Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/exporter.go
Labels: approved, lgtm, size/XS

#484 CI was here...:fire:
  ci
Labels: approved, lgtm, size/XS

#494 Remove 4.2 and use only 43/44/45 runs for _release_ branches
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#498 Brokers are now there twice, so we two filters, and two ingress
  Makefile
  openshift/ci-operator/generate-dockerfiles.sh
Labels: approved

#499 Consistent and unique container names
  config/brokers/channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/500-controller.yaml
  config/channels/in-memory-channel/500-dispatcher.yaml
  config/core/deployments/sources-controller.yaml
  openshift/release/knative-eventing-v0.13.0.yaml
Labels: approved, lgtm

#504 Create separate mtbroker release artifact
  openshift/release/generate-release.sh
Labels: approved, lgtm

#506 CI was here...:fire:
  ci
Labels: approved, lgtm

#507 Remove all category from internal API ...
  config/brokers/channel-broker/resources/configmappropagation.yaml
Labels: approved, lgtm
