Repository openshift/knative-eventing, pull requests merged in 2020-05, with the labels that each got.

#570 Adding a few more hacks for 'propper' image names on OCP... :fire:
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm

#575 Operator install and CI tests
  ci
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#581 Stash the file on the right place
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm

#582 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#586 Reflecting new configs and stuff
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm

#596 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream

#597 Use image template
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm
