Repository openshift/knative-eventing, pull requests merged in 2020-02, with the labels that each got.

#411 updating to latest Serverless Operator
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XL

#419 Go with the new APIGroup for the Knative Serving install
  openshift/e2e-tests-openshift.sh
Labels: lgtm, size/XS

#423 SRVKE-308 failurePolicy: Ignore for sinkbindings webhooks
  config/500-webhook-configuration.yaml
  openshift/e2e-tests-openshift.sh
  openshift/release/knative-eventing-v0.12.0.yaml
Labels: approved, lgtm, size/S

#425 Iincreasing timeout
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#426 SRVKE-310 update namespaced aggregate roles for apigroup changes
  config/200-clusterrole-namespaced.yaml
  openshift/release/knative-eventing-v0.12.0.yaml
Labels: approved, lgtm, size/M

#429 Using latest version
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/L

#431 Adding latest from 0.13_prep
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/L

#433 pointing to branch, instead of head
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm, size/XS

#434 fixing broken resolvr script
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XS

#440 pointing to nightly
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: size/S
