Repository openshift/knative-eventing, pull requests merged in 2020-12, with the labels that each got.

#1010 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#1006 [head] Adding back the image mirror, but only for test images.
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1005 [0.19] Adding back the image mirror, but only for test images.
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1012 [0.18] Adding OCP 4.7 run to CI job
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1015 using the proper name for the mirrored images to quay.io
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1017 making the generator script easier to read
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1020 [0.18] backport of upstream 0.19+ fix
  config/core/deployments/pingsource-mt-adapter.yaml
  pkg/adapter/v2/config.go
  pkg/adapter/v2/config_test.go
Labels: approved, lgtm

#1021 [0.18] Setting replica in yaml to 1, and regenerate the file
  config/core/deployments/pingsource-mt-adapter.yaml
  openshift/release/knative-eventing-ci.yaml
Labels: approved, lgtm

#1027 [0.19.2] Porting 4640 to OCP
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  openshift/release/knative-eventing-ci.yaml
Labels: approved, lgtm

#1028 [0.18.6] Porting 4640 to OCP
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  openshift/release/knative-eventing-ci.yaml
Labels: approved, lgtm

#1026 [HEAD] Adding 4.7 CI generator script
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1025 [0.19] Adding 4.7 CI generator script
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1030 Using latest of product
  openshift/e2e-common.sh
Labels: approved, lgtm

#1024 Adding teardown of eventing
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#1029 Using latest of product
  openshift/e2e-common.sh
Labels: approved, lgtm

#1034 Adding teardown to master_stash
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#1039 [0.19.2] Skip a test
  test/e2e/broker_with_many_triggers_test.go
Labels: approved, area/test-and-release, lgtm

#1040 Add patch to skip brokermanytriggers 4.7 failure for release-next
  openshift/patches/017-brokerManyTestsSkip.patch
Labels: approved, lgtm

#1049 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream
