Repository openshift/knative-eventing, pull requests merged in 2020-10, with the labels that each got.

#863 [0.16] using fqn image name
  openshift/ci-operator/build-image/Dockerfile
Labels: approved

#871 backport upstream 4168 to out .17
  config/core/deployments/webhook.yaml
Labels: approved, lgtm

#870 backport upstream 4168 to out .16
  config/core/deployments/webhook.yaml
Labels: approved, lgtm

#874 Using OC instead of k alias
  openshift/e2e-common.sh
Labels: approved, lgtm

#875 Reflecting some changes, over the years
  OWNERS_ALIASES
Labels: approved, lgtm

#878 adding migrator image change, and adding periodic test hook
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm

#877 adding migrator image change, and adding periodic test hook
  openshift/ci-operator/generate-ci-config.sh
Labels: approved

#881 Regenerating the release yaml, based on patches
  openshift/release/knative-eventing-ci.yaml
Labels: approved, lgtm

#885 [master] Going back to for loop for image builds
  Makefile
Labels: approved, lgtm

#884 [0.16] Going back to for loop for image builds
  Makefile
Labels: approved, lgtm

#888 [0.18] Going back to for loop for image builds
  Makefile
Labels: approved, lgtm

#883 [0.17] Going back to for loop for image builds
  Makefile
Labels: approved, lgtm

#887 Adding one more sinkbinding test to the list of skipped tests
  openshift/patches/015-sinkbinding_v1_tests_skip.patch
Labels: approved, lgtm

#896 Reduce the parallel to avoid timeouts
  openshift/e2e-common.sh
Labels: approved, lgtm

#893 backport of 4280
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: approved, lgtm

#898 [0.17] Port new recordevents
  go.sum
  openshift/e2e-common.sh
  test/conformance/helpers/broker_control_plane_test_helper.go
  test/conformance/helpers/broker_data_plane_test_helper.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_status_subscriber_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing_test_helper.go
  test/e2e/helpers/broker_channel_flow_helper.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/e2e/helpers/sequence_test_helper.go
  test/e2e/helpers/trigger_no_broker_test_helper.go
  test/lib/client.go
  test/lib/k8s_events.go
  test/lib/recordevents/event_info.go
  test/lib/recordevents/event_info_store.go
  test/lib/recordevents/event_info_store_test.go
  test/lib/recordevents/event_log.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/observer/reply.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/recorder_vent/doc.go
  test/lib/recordevents/recorder_vent/recorder.go
  test/lib/recordevents/resources.go
  test/lib/resources/kube.go
  test/test_images/recordevents/eventstore.go
  test/test_images/recordevents/eventstore_test.go
  test/test_images/recordevents/main.go
Labels: area/test-and-release

#897 [0.17] Updating the product base to 1.10 release
  openshift/e2e-common.sh
  openshift/serverless.bash
Labels: approved, lgtm

#900 Removing 4.5 channel, we are defaulting to 4.6
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#901 [0.18] align with release-17
  openshift/e2e-common.sh
Labels: approved, lgtm

#902 Go w/ 4 parallel
  openshift/e2e-common.sh
Labels: approved

#904 fixing the namespace problem for config-tracing and removing upstream flake
  openshift/e2e-common.sh
  openshift/patches/016_TestChannelChainV1beta1.patch
Labels: approved, lgtm

#908 [0.17] Separate e2e and conformance tests, like done on upstream
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#909 Some rel next improvements
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  openshift/patches/012-skip-tracing-conformance.patch
Labels: approved, lgtm

#910 Publish manually events to avoid event correlator (#4373) (#4386)
  test/lib/recordevents/recorder_vent/constructor.go
Labels: approved, area/test-and-release, lgtm

#916 Move around the functions for installing/configuration tracing
  openshift/e2e-common.sh
Labels: approved, lgtm

#917 Port recordevents updates
  test/lib/dropevents/receiver.go
  test/lib/recordevents/event_info.go
  test/lib/recordevents/logger_vent/logger.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/recorder_vent/recorder.go
  test/lib/test_runner.go
  test/test_images/recordevents/main.go
Labels: approved, area/test-and-release, lgtm

#919 Using hack repo
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#921 Backport wathola configurability
  test/upgrade/README.md
  test/upgrade/probe_test.go
  test/upgrade/prober/config.toml
  test/upgrade/prober/configuration.go
  test/upgrade/prober/forwarder.go
  test/upgrade/prober/prober.go
  test/upgrade/prober/prober_test.go
  test/upgrade/prober/receiver.go
  test/upgrade/prober/sender.go
Labels: approved, area/test-and-release, lgtm

#923 [0.17] Fix #4425
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, lgtm

#924 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#929 [0.17] Enable tracing
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#922 use beta1 pingsrc
  test/e2e/trigger_dependency_annotation_test.go
Labels: approved, area/test-and-release

#931 Release-next: tweaks
  openshift/e2e-common.sh
Labels: approved, lgtm

#932 [0.17] Bump parallel
  openshift/e2e-common.sh
Labels: approved, lgtm

#933 Backport of 4421 review changes
  test/upgrade/prober/configuration.go
  test/upgrade/prober/forwarder.go
  test/upgrade/prober/prober_test.go
  test/upgrade/prober/receiver.go
  test/upgrade/prober/sender.go
Labels: approved, area/test-and-release, lgtm

#934 Enable tracing and e2e bump 0.18
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#935 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#937 [release-v0.17.2] Backport: PR 4442
  test/upgrade/probe_test.go
Labels: approved, area/test-and-release, lgtm

#939 [release-v0.17.2] Hotfix: Use deployment to avoid disparity in effective user
  test/upgrade/prober/receiver.go
  test/upgrade/prober/sender.go
Labels: approved, area/test-and-release, lgtm
