Repository openshift/knative-eventing, pull requests merged in 2020-09, with the labels that each got.

#801 Regenerating the release yaml
  openshift/release/knative-eventing-ci.yaml
Labels: approved, lgtm

#806 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#807 Some little test fix / backport
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, lgtm

#810 Skipping tests, like on all other brnaches
  test/e2e/source_sinkbinding_v1alpha1_test.go
  test/e2e/source_sinkbinding_v1alpha2_test.go
Labels: approved, area/test-and-release, lgtm

#818 Using latest product for 017 branch
  openshift/e2e-common.sh
  openshift/serverless.bash
Labels: approved, lgtm

#822 Cherry pick 4042 and port to this branch
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, lgtm

#828 correct patch for sink binding mode in webhook
  openshift/patches/013-sinkbinding_webhook_corrections.patch
Labels: approved, lgtm

#827 Modify scripts to be reusable in serverless-operator repo (#673)
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#831 Set TEST_EVENTING_NAMESPACE properly - master
  openshift/e2e-common.sh
Labels: approved, lgtm

#830 Set TEST_EVENTING_NAMESPACE properly - release-v0.16.0
  openshift/e2e-common.sh
Labels: approved, lgtm

#832 Set TEST_EVENTING_NAMESPACE properly - 0.17.2
  openshift/e2e-common.sh
Labels: approved, lgtm

#836 Do not source test/e2e-common.sh
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#838 Do not source test/e2e-common.sh - master
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#840 We run Strimzi/Kafka in contrib
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#839 using oc replace in pipe
  openshift/e2e-common.sh
Labels: approved, lgtm

#841 We run Strimzi/Kafka in contrib
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#842 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#843 Using oc replace in pipe
  openshift/e2e-common.sh
Labels: approved, lgtm

#837 Do not source test/e2e-common.sh - release-v0.17.2
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#845 Port 4093 to our 0.16
  test/lib/duck/resource_checks.go
Labels: approved, area/test-and-release, lgtm

#850 Install yq in the build image for CI
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#851 Install yq in the build image for CI
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#849 Install yq in the build image for CI
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#848 backporting fix for default exponential backoff calculation (#4116)
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, lgtm

#846 Port 4093 to our 0.17
  test/lib/duck/resource_checks.go
Labels: approved, area/test-and-release, lgtm

#852 using oc replace in pipe
  openshift/e2e-common.sh
Labels: approved, lgtm

#857 Set check retry function (#4114)
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
  test/e2e/helpers/broker_redelivery_helper.go
Labels: approved, area/test-and-release, lgtm

#860 [0.16] Using fqn image name
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#859 [master] Using fqn image name
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#861 [0.17] Using fqn image name
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#862 [0.17] using fqn image name
  openshift/ci-operator/build-image/Dockerfile
Labels: approved
