Repository openshift/knative-eventing, pull requests merged in 2020-08, with the labels that each got.

#736 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#735 SRVKE-472: reenable flows e2e tests
  openshift/e2e-tests-openshift.sh
  test/e2e/parallel_test.go
  test/e2e/sequence_test.go
Labels: approved, area/test-and-release, lgtm

#741 Drop OCP 43 and 44 from nightly ci
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#751 Apply invokefix master
  openshift/e2e-common.sh
Labels: approved, lgtm

#757 Adding httpd-tools
  openshift/ci-operator/build-image/Dockerfile
Labels: approved

#756 Move forward w/ new bundle, and skip binding tests
  openshift/e2e-common.sh
  openshift/olm/serverless-operator.clusterserviceversion.yaml
  test/e2e/source_sinkbinding_v1alpha1_test.go
  test/e2e/source_sinkbinding_v1alpha2_test.go
Labels: approved, area/test-and-release, lgtm

#758 Adding httpd-tools
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#761 :robot: CI was here...:fire:
  ci
Labels: approved, lgtm

#762 CI was here to promote an image!
  ci
Labels: approved, kind/sync-fork-to-upstream

#763 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#766 Adding conformance test for OCP run
  openshift/e2e-common.sh
  openshift/patches/012-skip-tracing-conformance.patch
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#767 Apply sink binding config
  openshift/patches/013-sinkbinding_webhook_corrections.patch
  openshift/patches/014-sinkbinding_tests_skip.patch
  openshift/release/generate-release.sh
Labels: approved, lgtm

#768 fixing double patches
  openshift/patches/014-sinkbinding_tests_skip.patch
Labels: approved, lgtm

#765 Use 1.8 serverless-operator for just serving, and install eventing directly
  openshift/e2e-common.sh
  openshift/olm/README.md
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/serverless.bash
Labels: approved, lgtm

#773 Adding CRD install label first, to avoid race
  openshift/e2e-common.sh
Labels: approved, lgtm

#775 Fixing the disabled image promotion for all branches
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#781 We no longer have the old channel broker
  openshift/e2e-common.sh
Labels: approved, lgtm

#787 [0.16] Updating linux container to have httpd-tools
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#788 [0.15] Updating linux container to have httpd-tools
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#782 Serverless 1.8 usage and carry on patches
  ci
  config/core/deployments/webhook.yaml
  config/core/webhooks/sinkbindings.yaml
  openshift/e2e-common.sh
  openshift/release/knative-eventing-channelbroker-ci.yaml
  openshift/release/knative-eventing-ci.yaml
  openshift/serverless.bash
  test/conformance/broker_tracing_test.go
  test/conformance/channel_tracing_test.go
  test/e2e/source_sinkbinding_v1alpha1_test.go
  test/e2e/source_sinkbinding_v1alpha2_test.go
Labels: approved, area/test-and-release, lgtm

#794 Correct the patch, since we no longer need to set to Ignore
  openshift/patches/013-sinkbinding_webhook_corrections.patch
Labels: approved, lgtm

#793 Apply carried patches.
  config/core/deployments/webhook.yaml
  openshift/patches/013-sinkbinding_webhook_corrections.patch
  openshift/release/knative-eventing-ci.yaml
  test/conformance/broker_tracing_test.go
  test/conformance/channel_tracing_test.go
  test/e2e/source_sinkbinding_v1alpha1_test.go
  test/e2e/source_sinkbinding_v1alpha2_test.go
  test/e2e/source_sinkbinding_v1beta1_test.go
Labels: approved, area/test-and-release, lgtm

#792 Adding the patch apply fu to the script for new release branches
  openshift/release/create-release-branch.sh
Labels: approved, lgtm

#795 SRVKE-514: Adding upstream backports we want in 0.17
  config/core/configmaps/default-broker-channel.yaml
  config/core/configmaps/default-channel.yaml
  pkg/apis/duck/v1alpha1/channelable_combined_types.go
  pkg/apis/duck/v1alpha1/channelable_combined_types_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types_test.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/eventing/v1beta1/trigger_types.go
  pkg/apis/eventing/v1beta1/trigger_validation.go
  pkg/apis/eventing/v1beta1/trigger_validation_test.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/channel/controller_test.go
  pkg/reconciler/channel/resources/channel.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/controller_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/sugar/filters_test.go
  pkg/reconciler/sugar/labels.go
  pkg/reconciler/sugar/trigger/trigger_test.go
  pkg/reconciler/testing/v1/channel.go
  pkg/reconciler/testing/v1/service.go
  pkg/reconciler/testing/v1/subscription.go
  test/conformance/helpers/channel.go
  test/conformance/helpers/channel_status_subscriber_test_helper.go
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release

#800 [backport] 0.17.2: Enqueue Triggers on Broker changes
  pkg/reconciler/mtbroker/trigger/controller.go
  pkg/reconciler/mtbroker/trigger/trigger.go
Labels: approved, lgtm
