Repository openshift/knative-eventing, pull requests merged in 2020-06, with the labels that each got.

#604 We do not have the Filter/Ingress for the ST broker anymore
  Makefile
Labels: approved, lgtm

#606 Use Golang 1.14 on container builds
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#610 Dockerfile for source image
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#611 Run only MT broker
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm

#608 Dockerfile for source image
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#609 Dockerfile for source image
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#619 Add Ahmed Abdalla to the OWNERS_ALIASES and reorderd the list
  OWNERS_ALIASES
Labels: approved, lgtm

#617 Remove the messaging v1alpha1 API invocation
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm

#621 Update all channels to beta......
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm

#623 CI was here...:fire:
  ci
Labels: approved

#625 CI was here...:fire:
  ci
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm

#631 Fix image names
  Makefile
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
Labels: approved

#638 Release script fixes
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
Labels: approved, lgtm

#639 CI test
  ci
Labels: approved, lgtm

#642 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#645 CI was here...:fire:
  ci
Labels: approved, lgtm

#630 Make running tests easier
  Makefile
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
  openshift/origin-e2e-job.yaml
Labels: approved, lgtm

#641 CI test (again)
  Makefile
  ci
  openshift/ci-operator/knative-images/broker_filter/Dockerfile
  openshift/ci-operator/knative-images/broker_ingress/Dockerfile
  openshift/e2e-tests-openshift.sh
  openshift/release/knative-eventing-channelbroker-ci.yaml
Labels: approved, do-not-merge/hold

#649 update-ci makefile target: allow for release-next branch
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#653 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#654 CI was here...:fire:
  ci
Labels: approved

#646 Dev experience master
  Makefile
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
  openshift/origin-e2e-job.yaml
Labels: approved, lgtm

#655 CI run
  ci
Labels: approved, lgtm

#640 Trying to use the 1.8.0 operator
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved

#637 Mt channel broker as default
  config/core/configmaps/default-broker.yaml
  openshift/e2e-common.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/serverless-operator.v1.8.0.clusterserviceversion.yaml
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-v0.14.2.yaml
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/testing/broker.go
  test/config/st-channel-broker.yaml
  test/e2e-common.sh
Labels: approved, area/test-and-release, lgtm

#661 Add STBroker bits
  Makefile
  openshift/ci-operator/knative-images/broker_filter/Dockerfile
  openshift/ci-operator/knative-images/broker_ingress/Dockerfile
  openshift/e2e-common.sh
  openshift/olm/knative-eventing.catalogsource.yaml
Labels: approved, lgtm

#663 CI was here :fire:
  ci
  openshift/e2e-common.sh
  openshift/release/knative-eventing-channelbroker-ci.yaml
Labels: approved

#664 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#665 CI was here...:fire:
  ci
Labels: approved, lgtm

#666 CI was here...:fire:
  ci
Labels: approved, lgtm

#667 Add OCP4.6 to ci generated yaml
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#660 generate-ci-config should use proper equality check for strings
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm

#669 CI for ocp46/v0.15.1
  ci
Labels: approved, lgtm

#681 CI :fire:
  ci
Labels: approved, lgtm

#682 CI test (e2e)
  ci
  openshift/release/knative-eventing-channelbroker-ci.yaml
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-mtbroker-ci.yaml
Labels: approved

#683 running ci now that images can be pulled
  ci
Labels: approved, lgtm
