Repository openshift/knative-eventing, pull requests merged in 2020-01, with the labels that each got.

#377 Prepare fix
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/patches/001-no-random-namespace-names.patch
  openshift/patches/004-flows-rbac.patch
  openshift/patches/005-flows-skip_tests.patch
Labels: size/XXL

#374 Script fixes
  Makefile
  openshift/ci-operator/knative-images/imc-controller/Dockerfile
  openshift/ci-operator/knative-images/imc-dispatcher/Dockerfile
  openshift/ci-operator/update-ci.sh
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-eventing.catalogsource.yaml
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-v0.11.0.yaml
  test/e2e/flows_parallel_test.go
  test/e2e/flows_sequence_test.go
Labels: approved, lgtm, size/XL

#384 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#386 Updating the serving/serverless yaml
  openshift/olm/knative-serving.catalogsource.yaml
Labels: size/L

#388 changing webhook nw policy apply mechanism
  openshift/999-webhook-policy_append.patch
  openshift/patches/003-webhook-policy.patch
  openshift/release/update-to-head.sh
Labels: size/M

#404 Adding yaml patch for server-side dry run
  openshift/release/knative-eventing-v0.11.0.yaml
Labels: approved, lgtm, size/XS

#413 Adjusting new team
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
