Repository openshift/knative-eventing, pull requests merged in 2021-01, with the labels that each got.

#1056 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#1057 [0.19.2] backport: add prom host (#4661)
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, lgtm

#1059 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#1062 Remove patch to skip TestChannelBasedBrokerWithManyTriggers
  openshift/patches/017-brokerManyTestsSkip.patch
Labels: approved, lgtm

#1065 Remove SpecificWaits Patch, re-add skip for flake
  openshift/patches/017-brokerManyTestsSkip.patch
  openshift/patches/017-brokerManyTestsSpecificWaits.patch
Labels: approved, lgtm

#1066 Fix patch file (was a patch of a git diff :facepalm:)
  openshift/patches/017-brokerManyTestsSkip.patch
Labels: approved

#1016 Help to improve the release doc
  RELEASE.md
Labels: approved, lgtm

#1067 Update release.md, readme.md
  README.md
  RELEASE.md
Labels: approved, lgtm

#1058 Adds skonto to owner_alias
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test

#1069 Add mirror-upstream-branches.sh script
  openshift/release/mirror-upstream-branches.sh
Labels: approved, lgtm

#1081 Automate adding reporter_config to update-ci script, add to readme
  openshift/ci-operator/update-ci.sh
  openshift/release/README.md
Labels: approved, lgtm

#1083 Using 1.15 on our linux container
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm
