Repository openshift/knative-eventing, pull requests merged in 2021-02, with the labels that each got.

#1097 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#1096 Run mirror-to-upstream-branch.sh script from nightly mirror
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#1099 Try increasing e2e timeout to 50m, drop brokerManyTestsSkip patch
  openshift/e2e-common.sh
  openshift/patches/017-brokerManyTestsSkip.patch
Labels: approved, lgtm

#1104 Expose runmaintest for upgrades
  test/upgrade/upgrade.go
  test/upgrade/upgrade_test.go
Labels: approved, area/test-and-release, lgtm

#1110 Add diagnostic messages to mirror-upstream-branches.sh
  openshift/release/mirror-upstream-branches.sh
Labels: approved, lgtm
