Repository openshift/knative-eventing, pull requests merged in 2021-06, with the labels that each got.

#1287 Fixing some scripts for 0.23 (and later)
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1288 A new image to replace
  openshift/patches/018-rekt-test-apiserversource_data_plane.patch
Labels: approved, lgtm

#1291 Adding temporary fix to skip one REKT test for futher investigations
  openshift/patches/018-rekt-test-skip-TestEventTransformationForSubscriptionV1.patch
Labels: approved, lgtm

#1294 [0.21] backport 1281, 1274, 1266 and 1223
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
Labels: approved, lgtm

#1295 Bump to Golang 1.16
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#1297 [main] Mute noisy metrics patch next
  openshift/patches/020-mutemetrics.patch
Labels: approved, lgtm

#1300 [0.23] SRVKE-796 patch
  pkg/reconciler/broker/broker.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
Labels: approved, lgtm

#1302 [release-22] Mute noisy metrics patch
  openshift/patches/020-mutemetrics.patch
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
Labels: approved, lgtm

#1303 Align the rekt test for 0.23 with the version images from the registry
  test/rekt/resources/containersource/containersource.yaml
  test/rekt/resources/containersource/containersource_test.go
  test/rekt/resources/eventlibrary/eventlibrary.yaml
  test/rekt/resources/eventlibrary/eventlibrary_test.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/flaker/flaker_test.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Labels: approved, area/test-and-release, lgtm

#1299 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#1293 Change the name of the mistream release branch to be just X.Y
  openshift/release/mirror-upstream-branches.sh
Labels: approved, lgtm

#1301 [release-23] mute noisy metrics patch
  openshift/patches/020-mutemetrics.patch
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
Labels: approved, lgtm

#1305 Adding timeput for e2e jobs to the generator script
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm

#1307 Add a check for an existing sync PR in the midstream repo
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#1311 [Release-v0.22.0][Backport] Make Channel metrics generic enough for eventing-kafka
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/stats_reporter.go
Labels: approved, lgtm

#1316 Pass transformers to executeRequest
  pkg/channel/message_dispatcher.go
Labels: approved, lgtm

#1318 [Backport] [Release 0.23] Use transformers to extract metrics for Kafka
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/message_dispatcher.go
  pkg/channel/stats_reporter.go
Labels: approved, lgtm

#1324 Add version suffix to registry mirroring generator script
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#1327 Using 1.16 version of product
  openshift/e2e-common.sh
Labels: approved, lgtm

#1328 Using 1.16 version of product
  openshift/e2e-common.sh
Labels: approved, lgtm
