Repository openshift/knative-eventing, pull requests merged in 2021-09, with the labels that each got.

#1390 [0.24] backports from upstream
  config/core/resources/trigger.yaml
  pkg/apis/sources/v1/ping_validation.go
  pkg/apis/sources/v1/ping_validation_test.go
  pkg/apis/sources/v1beta2/ping_validation.go
  pkg/apis/sources/v1beta2/ping_validation_test.go
  test/experimental/delivery_timeout_test.go
  test/rekt/features/broker/readyness.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/broker/broker.yaml
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/trigger/trigger.go
  test/rekt/resources/trigger/trigger.yaml
Labels: lgtm, approved, area/test-and-release

#1394 [release-v0.24] Do not set TEST_IMAGE_TEMPLATE in e2e-commons.sh
  openshift/e2e-common.sh
  openshift/e2e-conformance-tests.sh
  openshift/e2e-rekt-tests.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: lgtm, approved

#1376 Some proposal for release scheduling
  README.md
Labels: lgtm, approved

#1397 Reduce eventing-reviewers alias to core eventing team
  OWNERS_ALIASES
Labels: lgtm, approved

#1398 Add CI Rotation for the team
  README.md
Labels: lgtm, approved

#1401 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#1396 [release-v0.24] Wait for test NS to be deleted after REKT tests
  openshift/e2e-common.sh
Labels: lgtm, approved, area/test-and-release

#1404 Fixing patch, to now also recognize the k8s labels
  openshift/patches/019-remove-tracing-observability-yamls.patch
Labels: lgtm, approved

#1395 [main] Do not set TEST_IMAGE_TEMPLATE in e2e-commons.sh
  openshift/e2e-common.sh
  openshift/e2e-conformance-tests.sh
  openshift/e2e-rekt-tests.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: lgtm, approved

#1385 [release-v0.25] Prepare for cluster pools
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-common.sh
  openshift/e2e-conformance-tests.sh
  openshift/e2e-rekt-tests.sh
  openshift/e2e-tests.sh
Labels: lgtm, approved

#1406 [main] Adding dptp change to job config generator
  openshift/ci-operator/generate-ci-config.sh
Labels: lgtm, approved

#1411 [release-v0.22.0] Use dependencies instead of IMAGE_FORMAT
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: lgtm, approved

#1415 [release-v0.25] Cherry pick the "real" fix for 1.22 compatibility
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, approved

#1419 [main] Using 1.18 product brnach
  openshift/e2e-common.sh
Labels: lgtm, approved

#1418 [release-v0.24] Using 1.18 product brnach
  openshift/e2e-common.sh
Labels: lgtm, approved

#1420 [release-v0.25] Using 1.18 product branch
  openshift/e2e-common.sh
Labels: lgtm, approved

#1402 Adjusting the table for release work
  README.md
Labels: approved

#1412 [release-v0.23] Use dependencies instead of IMAGE_FORMAT and switch to cluster pool
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-common.sh
  openshift/e2e-conformance-tests.sh
  openshift/e2e-rekt-tests.sh
  openshift/e2e-tests.sh
Labels: lgtm, approved

#1424 Switch CI duty with Ali
  README.md
Labels: lgtm, approved

#1425 [release-v0.25] Adding 4.9 for ci generator
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: lgtm, approved

#1426 [release-v0.25] Backport: DeliverySpec.Timeout on Broker and Trigger (#5689)
  config/core/resources/trigger.yaml
  test/experimental/delivery_timeout_test.go
  test/rekt/features/broker/readyness.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/broker/broker.yaml
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/trigger/trigger.go
  test/rekt/resources/trigger/trigger.yaml
Labels: lgtm, approved, area/test-and-release

#1422 Drop the subresource patch
  openshift/patches/005-subresource.patch
Labels: lgtm, approved

#1428 [main] Go with latest for zipkin... same like on Serverless Product repo
  openshift/e2e-common.sh
Labels: lgtm, approved

#1429 [release-v0.25] Let's not hard code here too...
  openshift/ci-operator/generate-ci-config.sh
Labels: lgtm, approved

#1431 Use version ghcr for zipkin:2
  openshift/e2e-common.sh
Labels: lgtm, approved
