Repository openshift/knative-eventing, pull requests merged in 2021-05, with the labels that each got.

#1236 Dockerfile update
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#1240 Using logger.info instead of header_text
  openshift/e2e-common.sh
Labels: approved, lgtm

#1235 poke ci
  ci
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
Labels: approved, lgtm

#1245 [0.20] Use the latest of OCP Serverless on 0.20 branch
  openshift/e2e-common.sh
Labels: approved, lgtm

#1243 [0.22] Use the latest of OCP Serverless on 0.22 branch
  openshift/e2e-common.sh
Labels: approved, lgtm

#1244 [0.21] Use the latest of OCP Serverless on 0.21 branch
  openshift/e2e-common.sh
Labels: approved, lgtm

#1242 [main] using logger.info instead of header_text (#1240)
  openshift/e2e-common.sh
Labels: approved, lgtm

#1241 [0.22] using logger.info instead of header_text (#1240)
  openshift/e2e-common.sh
Labels: approved, lgtm

#1247 Adding the eventhub image to the list of test images
  Makefile
Labels: approved, lgtm

#1248 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#1246 [main] Use the latest of OCP Serverless on main branch
  openshift/e2e-common.sh
Labels: approved, lgtm

#1251 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#1253 update CI yamls for 0.16.0
  openshift/e2e-common.sh
  openshift/release/generate-release.sh
  openshift/release/knative-eventing-channelbroker-ci.yaml
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-mtbroker-ci.yaml
Labels: approved, lgtm

#1260 Removing the beta source APIs
  openshift/e2e-common.sh
Labels: approved, lgtm

#1261 [main] Imc generation patch
  openshift/patches/019-remove-tracing-observability-yamls.patch
  openshift/release/generate-release.sh
Labels: approved, lgtm

#1271 [RELEASE-v0.22.0] Use new label for defining a cluster-local Knative Service
  test/upgrade/prober/forwarder.go
Labels: approved, area/test-and-release, lgtm

#1270 [RELEASE-v0.21.0] Use new label for defining a cluster-local Knative Service
  test/upgrade/prober/forwarder.go
Labels: approved, area/test-and-release, lgtm

#1272 Adding downstream checks for KafkaChannel v1a1
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/mtbroker/broker.go
Labels: approved, lgtm

#1273 [0.22] Tweak channel template
  pkg/reconciler/broker/broker.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  test/e2e/channel_chain_test.go
Labels: approved, area/test-and-release, lgtm

#1274 [Backport] Allow URIs to be resolved without reconciler context (#2095)
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
Labels: approved, lgtm

#1275 [Backport] Allow URIs to be resolved without reconciler context (#2095)
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
Labels: approved, lgtm

#1276 [0.21] Using the Serverless 1.15 product
  openshift/e2e-common.sh
Labels: approved, lgtm

#1277 [0.22] Using the Serverless 1.15 product
  openshift/e2e-common.sh
Labels: approved, lgtm

#1279 Using 1.16 on our linux container
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#1281 [RELEASE-v0.21.0] Rollback certificate algorithm changes
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
Labels: approved, lgtm

#1283 [0.23] Rollback certificate algorithm changes (#1281)
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
Labels: approved, lgtm

#1282 [0.22] Rollback certificate algorithm changes (#1281)
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
Labels: approved, lgtm

#1286 [0.21] Backport of knative#5444
  test/upgrade/prober/sut/broker.go
  test/upgrade/prober/sut/broker_e2e_test.go
Labels: approved, area/test-and-release, lgtm
