Repository openshift/knative-eventing, pull requests merged in 2021-04, with the labels that each got.

#1185 [0.20] Disable repo_gpgcheck for kube repo in build image
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved

#1186 [0.20] CI was here...:fire:
  ci
Labels: approved, lgtm

#1189 :robot: CI was here...:fire:
  ci
Labels: approved, lgtm

#1192 Add patch to filter out non-duck apis
  openshift/patches/017-SourceCRDControllerFilterNonDucks.patch
Labels: approved, lgtm

#1190 source.crd controller: filter out non duck crds
  pkg/reconciler/source/crd/crd.go
  pkg/reconciler/source/crd/crd_test.go
Labels: approved, lgtm

#1191 Source crd cherry pick v21
  pkg/reconciler/source/crd/crd.go
  pkg/reconciler/source/crd/crd_test.go
Labels: approved, lgtm

#1193 Upstream did drop the v1beta, correcting our test execution for channels
  openshift/e2e-common.sh
Labels: approved, lgtm

#1213 [0.21] KafkaChannel hack to upgrade (#5085)
  pkg/apis/messaging/v1/subscription_defaults.go
  pkg/apis/messaging/v1/subscription_validation.go
  pkg/apis/messaging/v1/subscription_validation_test.go
  pkg/apis/messaging/v1beta1/subscription_defaults.go
  pkg/apis/messaging/v1beta1/subscription_validation.go
  pkg/apis/messaging/v1beta1/subscription_validation_test.go
Labels: approved, lgtm

#1217 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#1219 [MAIN] Update source versions on e2e/conformance tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#1221 [0.21] Align the source version schema for our 0.21 branch
  openshift/e2e-common.sh
Labels: approved, lgtm

#1220 [0.22] Align the source version schema for our 0.22 branch
  openshift/e2e-common.sh
Labels: approved, lgtm

#1226 [0.22.0] backport CreatePodOrFail retry on "No API token found" (#5313)
  test/lib/creation.go
Labels: approved, area/test-and-release, lgtm

#1227 [0.21.0] backport CreatePodOrFail retry on "No API token found" (#5313)
  test/lib/creation.go
Labels: approved, area/test-and-release, lgtm

#1228 [0.20.0] backport CreatePodOrFail retry on "No API token found" (#5313)
  test/lib/creation.go
Labels: approved, area/test-and-release, lgtm

#1229 Upstream removed the v1alpha1 tests
  openshift/patches/014-sinkbinding_tests_skip.patch
Labels: approved, lgtm

#1223 [SRVKS-720] Mute noisy metrics controller & webhook
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
Labels: approved, lgtm

#1232 Upstream removed the v1alpha2 tests
  openshift/patches/014-sinkbinding_tests_skip.patch
Labels: approved, lgtm

#1230 Remove sinkbinding tests for beta1 patch
  openshift/patches/014-sinkbinding_tests_skip.patch
Labels: approved, lgtm
