Repository openshift/knative-eventing, pull requests merged in 2021-08, with the labels that each got.

#1348 Patch the rekt for 0.24 too
  vendor/knative.dev/reconciler-test/pkg/images/ko.go
Labels: approved, lgtm

#1351 [release-v0.24] Backport of run conformance tests as project admin
  test/conformance/README.md
  test/conformance/broker_tracing_test.go
  test/conformance/channel_addressable_resolver_cluster_role_test.go
  test/conformance/channel_channelable_manipulator_cluster_role_test.go
  test/conformance/channel_crd_metadata_test.go
  test/conformance/channel_tracing_test.go
  test/conformance/create-namespace-rbac.sh
  test/conformance/main_test.go
  test/conformance/source_crd_metadata_test.go
  test/conformance/source_crd_rbac_test.go
  test/conformance/source_crd_registry_test.go
  test/lib/creation.go
  test/lib/recordevents/resources.go
  test/lib/setupclientoptions/sources.go
  test/lib/test_runner.go
Labels: approved, area/test-and-release, lgtm

#1350 [release-v0.23] Backports for conformance tests
  test/conformance/README.md
  test/conformance/broker_tracing_test.go
  test/conformance/channel_addressable_resolver_cluster_role_test.go
  test/conformance/channel_channelable_manipulator_cluster_role_test.go
  test/conformance/channel_crd_metadata_test.go
  test/conformance/channel_tracing_test.go
  test/conformance/create-namespace-rbac.sh
  test/conformance/main_test.go
  test/conformance/source_crd_metadata_test.go
  test/conformance/source_crd_rbac_test.go
  test/conformance/source_crd_registry_test.go
  test/e2e/main_test.go
  test/e2e_flags.go
  test/flags/eventing_environment.go
  test/lib/creation.go
  test/lib/recordevents/resources.go
  test/lib/setupclientoptions/sources.go
  test/lib/test_runner.go
Labels: approved, area/test-and-release, lgtm

#1361 [SRVKS-790] Patch subresource to unblock webhooks on 4.9
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
Labels: lgtm, approved

#1370 [0.25] Use 1.17 product branch
  openshift/e2e-common.sh
Labels: lgtm, approved, do-not-merge/hold

#1369 [main] Use 1.17 product branch
  openshift/e2e-common.sh
Labels: lgtm, approved

#1367 [0.23] Use 1.17 product branch
  openshift/e2e-common.sh
Labels: lgtm, approved

#1368 [0.24] Use 1.17 product branch
  openshift/e2e-common.sh
Labels: lgtm, approved

#1371 [RELEASE-v0.23] Use v1 CRD clients in tests
  test/lib/client.go
Labels: lgtm, approved, area/test-and-release

#1366 [0.25] Patch subresource to unblock webhooks on 4.9 (#1361)
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
Labels: lgtm, approved

#1375 [RELEASE-v0.25] Use v1 CRD clients in tests
  test/lib/client.go
Labels: lgtm, approved, area/test-and-release

#1374 [RELEASE-v0.24] Use v1 CRD clients in tests
  test/lib/client.go
Labels: lgtm, approved, area/test-and-release

#1365 [0.24] Patch subresource to unblock webhooks on 4.9 (#1361)
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
Labels: lgtm, approved

#1378 [release-v0.24] Prepare for cluster pools
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-common.sh
  openshift/e2e-conformance-tests.sh
  openshift/e2e-rekt-tests.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: lgtm, approved

#1384 [release-v0.24] Generate cluster pool stanza for OCP 4.8
  openshift/ci-operator/generate-ci-config.sh
Labels: lgtm, approved

#1377 [main] Prepare for cluster pools (remove IMAGE_FORMAT, generate cluster-pool)
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-common.sh
  openshift/e2e-conformance-tests.sh
  openshift/e2e-rekt-tests.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: lgtm, approved

#1386 Adding patch for OCP 4.9, like done on older release branches (0.24+)
  openshift/patches/005-subresource.patch
Labels: lgtm, approved
