Repository openshift/knative-eventing, pull requests merged in 2022-04, with the labels that each got.

#1687 [main] updating a patch
  openshift/patches/019-remove-tracing-observability-yamls.patch
Labels: lgtm, approved

#1688 Remove unneeded patch
  openshift/patches/019-remove-tracing-observability-yamls.patch
Labels: lgtm, approved

#1689 Remove sugar controller since it was merged
  openshift/e2e-common.sh
Labels: lgtm, approved

#1653 [release-v1.1] Set dead letter sink URI in the `Channel` status (#6256) (#6263)
  config/core/resources/channel.yaml
  docs/eventing-api.md
  pkg/apis/messaging/v1/channel_template_types.go
  test/rekt/channel_test.go
  test/rekt/features/channel/features.go
  test/rekt/resources/channel/channel.go
  test/rekt/resources/channel/channel_test.go
  test/rekt/resources/channel_impl/channel_impl.go
Labels: lgtm, approved, area/test-and-release

#1693 Resolve testing configuration for sugar controller
  openshift/release/generate-release.sh
Labels: lgtm, approved

#1694 Prepare for future version when generating the periodics
  openshift/ci-operator/generate-ci-config.sh
Labels: lgtm, approved

#1695 [release-v1.2] Update images to new version
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-mtbroker-ci.yaml
Labels: lgtm, approved

#1696 Upate the min version
  openshift/patches/005-k8s-min.patch
Labels: lgtm, approved

#1707 [release-v1.4] NPE fix (#6343)
  test/upgrade/prober/verify.go
Labels: lgtm, approved, area/test-and-release

#1704 [release-v1.3] Adding 4.10 and do nightly periodics there, as well as image promotion
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: lgtm, approved

#1706 [release-v1.2] Backport upgrade event tracing
  test/config/monitoring/monitoring.yaml
  test/lib/client.go
  test/lib/creation.go
  test/test_images/utils.go
  test/upgrade/README.md
  test/upgrade/prober/config.toml
  test/upgrade/prober/configuration.go
  test/upgrade/prober/forwarder.go
  test/upgrade/prober/receiver.go
  test/upgrade/prober/sender.go
  test/upgrade/prober/verify.go
  test/upgrade/prober/wathola/client/receiver.go
  test/upgrade/prober/wathola/config/defaults.go
  test/upgrade/prober/wathola/config/structure.go
  test/upgrade/prober/wathola/config/tracing.go
  test/upgrade/prober/wathola/event/services.go
  test/upgrade/prober/wathola/event/tracing.go
  test/upgrade/prober/wathola/event/tracing_test.go
  test/upgrade/prober/wathola/forwarder/services.go
  test/upgrade/prober/wathola/receiver/services.go
  test/upgrade/prober/wathola/receiver/services_test.go
  test/upgrade/prober/wathola/sender/operations.go
  test/upgrade/prober/wathola/sender/services.go
  test/upgrade/prober/wathola/sender/services_test.go
  test/upgrade/prober/wathola/sender/types.go
  test/upgrade/upgrade.go
  vendor/github.com/openzipkin/zipkin-go/reporter/recorder/recorder.go
  vendor/knative.dev/pkg/tracing/testing/zipkin.go
  vendor/modules.txt
Labels: lgtm, approved, area/test-and-release

#1708 Porting 1704 to main
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: lgtm, approved

#1711 Release v1.4
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: lgtm, approved, area/test-and-release

#1717 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1705 [release-v1.2] Adding 4.10 and do nightly periodics there, as well as image promotion
  openshift/ci-operator/update-ci.sh
Labels: lgtm, approved

#1720 Do not populare the Eventing CI files with testing bits
  openshift/e2e-common.sh
  openshift/release/generate-release.sh
Labels: lgtm, approved

#1722 Do not proxy some headers from reply
  pkg/broker/filter/filter_handler.go
Labels: lgtm, approved
