Repository openshift/knative-eventing, pull requests merged in 2022-01, with the labels that each got.

#1579 Update CI duty table
  README.md
Labels: lgtm, approved

#1581 [release-1.1] Actual version for rekt test
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/resources/containersource/containersource.yaml
  test/rekt/resources/containersource/containersource_test.go
  test/rekt/resources/eventlibrary/eventlibrary.yaml
  test/rekt/resources/eventlibrary/eventlibrary_test.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/flaker/flaker_test.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Labels: lgtm, approved, area/test-and-release

#1583 Remove hard-coded 4.8 version
  openshift/ci-operator/generate-ci-config.sh
Labels: lgtm, approved

#1584 Fix #1578 on main
  Makefile
  openshift/ci-operator/Dockerfile_with_kodata.in
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/e2e-common.sh
Labels: lgtm, approved

#1585 Fix k8s-min patch
  openshift/patches/005-k8s-min.patch
Labels: lgtm, approved

#1590 [release-v1.0] Prober waits until receiver state != active or timeout
  test/upgrade/prober/configuration.go
  test/upgrade/prober/prober.go
  test/upgrade/prober/verify.go
Labels: lgtm, approved, area/test-and-release

#1593 Remove knative- from the release generator script
  openshift/release/generate-release.sh
Labels: lgtm, approved

#1594 [release-v1.1] Fix wrong image names in generated manifests
  openshift/release/knative-eventing-ci.yaml
  openshift/release/knative-eventing-mtbroker-ci.yaml
Labels: lgtm, approved

#1596 Update ci duty schedule
  README.md
Labels: lgtm, approved

#1597 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1598 [SRVKE-1046] Remove skip TestTriggerWithDLS patch
  openshift/patches/021-rekt-skip-test-trigger.patch
Labels: lgtm, approved
