Repository openshift/knative-eventing, pull requests merged in 2022-03, with the labels that each got.

#1649 Fix rekt-test-image-changes patch
  openshift/patches/018-rekt-test-image-changes.patch
Labels: lgtm, approved

#1652 [release-1.3] Set dead letter sink URI in the `Channel` status (#6261)
  config/core/resources/channel.yaml
  docs/eventing-api.md
  pkg/apis/messaging/v1/channel_template_types.go
  test/rekt/channel_test.go
  test/rekt/features/channel/features.go
  test/rekt/resources/channel/channel.go
  test/rekt/resources/channel/channel_test.go
  test/rekt/resources/channel_impl/channel_impl.go
Labels: lgtm, approved, area/test-and-release

#1654 [SRVKE-1181] Skip GPG check for kubernetes repository
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved

#1655 [release-v1.0] backport of 6264
  config/core/resources/channel.yaml
  docs/eventing-api.md
  pkg/apis/messaging/v1/channel_template_types.go
  test/rekt/channel_test.go
  test/rekt/features/channel/features.go
  test/rekt/resources/channel/channel.go
  test/rekt/resources/channel/channel_test.go
  test/rekt/resources/channel_impl/channel_impl.go
Labels: approved, area/test-and-release

#1663 [release-v1.0] Fix channel template spec type for sequence channel template field
  config/core/resources/sequence.yaml
  openshift/release/knative-eventing-ci.yaml
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  test/rekt/features/parallel/readyness.go
  test/rekt/features/sequence/readyness.go
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/parallel/parallel.go
  test/rekt/resources/parallel/parallel.yaml
  test/rekt/resources/parallel/parallel_test.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/resources/sequence/sequence.yaml
  test/rekt/resources/sequence/sequence_test.go
  test/rekt/smoke_test.go
Labels: lgtm, approved, area/test-and-release

#1668 [release-1.0] Backport of upstream 6265
  pkg/reconciler/broker/trigger/controller.go
  pkg/reconciler/broker/trigger/controller_test.go
  pkg/reconciler/broker/trigger/trigger.go
Labels: lgtm, approved

#1651 [release-1.2] Set dead letter sink URI in the `Channel` status (#6262)
  config/core/resources/channel.yaml
  docs/eventing-api.md
  pkg/apis/messaging/v1/channel_template_types.go
  test/rekt/channel_test.go
  test/rekt/features/channel/features.go
  test/rekt/resources/channel/channel.go
  test/rekt/resources/channel/channel_test.go
  test/rekt/resources/channel_impl/channel_impl.go
Labels: lgtm, approved, area/test-and-release

#1674 Increase rekt tests timeout to 1h
  openshift/e2e-common.sh
Labels: lgtm, approved

#1679 Remove devguyio OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved
