Repository openshift/knative-eventing, pull requests merged in 2022-11, with the labels that each got.

#1908 [release-v1.6] Add new readiness hooks to manifest
  openshift/release/artifacts/eventing-core.yaml
Labels: approved

#1910 [release-v1.5] Set SecurityContext for test Pods
  test/lib/creation.go
  test/rekt/resources/eventlibrary/eventlibrary.go
  test/rekt/resources/eventlibrary/eventlibrary.yaml
  test/rekt/resources/flaker/flaker.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/pod/pod.go
  test/rekt/resources/pod/pod.yaml
  vendor/knative.dev/pkg/test/security/security.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
Labels: lgtm, approved, area/test-and-release

#1914 [release-v1.4] Set SecurityContext for test Pods
  test/lib/creation.go
  test/rekt/resources/eventlibrary/eventlibrary.go
  test/rekt/resources/eventlibrary/eventlibrary.yaml
  test/rekt/resources/flaker/flaker.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/pod/pod.go
  test/rekt/resources/pod/pod.yaml
  vendor/knative.dev/pkg/test/security/security.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
Labels: lgtm, approved, area/test-and-release

#1911 [release-v1.6] Set SecurityContext for test Pods
  test/lib/creation.go
  test/rekt/resources/eventlibrary/eventlibrary.go
  test/rekt/resources/eventlibrary/eventlibrary.yaml
  test/rekt/resources/flaker/flaker.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/pod/pod.go
  test/rekt/resources/pod/pod.yaml
  vendor/knative.dev/pkg/test/security/security.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
Labels: lgtm, approved, area/test-and-release

#1912 [release-v1.7] Set SecurityContext for test Pods
  test/lib/creation.go
  test/rekt/resources/eventlibrary/eventlibrary.go
  test/rekt/resources/eventlibrary/eventlibrary.yaml
  test/rekt/resources/flaker/flaker.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/pod/pod.go
  test/rekt/resources/pod/pod.yaml
  vendor/knative.dev/pkg/test/security/security.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
Labels: lgtm, approved, area/test-and-release

#1913 [release-v1.8] Set SecurityContext for test Pods
  test/lib/creation.go
  test/rekt/resources/eventlibrary/eventlibrary.go
  test/rekt/resources/eventlibrary/eventlibrary.yaml
  test/rekt/resources/flaker/flaker.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/pod/pod.go
  test/rekt/resources/pod/pod.yaml
  vendor/knative.dev/pkg/test/security/security.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
Labels: lgtm, approved, area/test-and-release

#1915 Add creydr to OWNER_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved

#1923 [release-v1.5] Decrease exportTraceLimit to 100
  test/upgrade/prober/verify.go
Labels: lgtm, approved, area/test-and-release

#1922 Fix tiny typo in release manual
  RELEASE.md
Labels: lgtm, approved

#1927 Fix patch after upstream changes for security context
  openshift/patches/018-rekt-test-image-changes.patch
Labels: lgtm, approved

#1928 [main] Patches to make OCP 48 -> OCP 4.11 work
  openshift/patches/keep_hpa_v2beta2_until_ocp_4.13.patch
  openshift/patches/remove_seccompProfile.patch
Labels: lgtm, approved

#1921 Add creydr to CI rotation table
  README.md
Labels: approved, do-not-merge/hold

#1932 [RELEASE-1.5] Use env configurator
  cmd/mtping/main.go
Labels: lgtm, approved

#1933 [main] Updating min version patch
  openshift/patches/005-k8s-min.patch
Labels: lgtm, approved

#1931 Make sure we also new files, created out of the git-apply command
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: lgtm, approved

#1934 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1935 State that this repo is not needed anymore
  README.md
Labels: lgtm, approved
