Repository openshift/knative-eventing, pull requests merged in 2022-05, with the labels that each got.

#1726 [release-v1.1] Set ARTIFACTS based on ARTIFACT_DIR provided in CI
  openshift/e2e-common.sh
Labels: lgtm, approved

#1735 Updates on how simple the release cut now is for midstream eventing
  RELEASE.md
Labels: lgtm, approved

#1736 Fix broken link
  RELEASE.md
Labels: lgtm, approved

#1737 [release-v1.2] Use versioned images for rekt tests
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/resources/containersource/containersource.yaml
  test/rekt/resources/containersource/containersource_test.go
  test/rekt/resources/eventlibrary/eventlibrary.yaml
  test/rekt/resources/eventlibrary/eventlibrary_test.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/flaker/flaker_test.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Labels: lgtm, approved, area/test-and-release

#1739 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1742 Remove skip statement for the TestEventTransformationForSubscriptionV1 test
  openshift/patches/018-rekt-test-skip-TestEventTransformationForSubscriptionV1.patch
Labels: lgtm, approved

#1713 Update CI to point at 4.9 and 4.10
  openshift/ci-operator/update-ci.sh
Labels: lgtm, approved

#1743 Improve eventing core scripts
  openshift/e2e-common.sh
  openshift/release/artifacts/knative-eventing-core.yaml
  openshift/release/artifacts/knative-eventing-imc.yaml
  openshift/release/artifacts/knative-eventing-mt-broker.yaml
  openshift/release/generate-release.sh
Labels: lgtm, approved
